### PR TITLE
update endpoint, remove first, last name

### PR DESCRIPTION
**Pull request by ros3bud**
This new endpoint and the removal of first and last name should be all that is needed here in order to update the integration so that it gives back home value, without requiring first and last name. 

@cgrayson , LGTY?

### CODE REVIEW

**Comment by cgrayson** [comment]
LGTM. I only wonder about your phrasing that it will now "give back home value, without requiring first and last name", as this change goes beyond "not requiring". It now can never use `first_name` and `last_name` in any case. Just double-checking that's the intent.

**Comment by ros3bud** [comment]
Yes, it is correct that first and last name will not be allowed for this. This is because the endpoint does nothing with that information. IE if they were sent, they would not affect the results. I think it's better to leave it out in order to make it clear that those values don't affect the data at all.

**Comment by ros3bud** [comment]
@cgrayson, I updated both integrations to make use of the environment variables as we discussed. LGTY?

**Comment by cgrayson** [comment]
:+1:

**Pull request merged**
